### ISSUE TITLE
Access to wallet

### ISSUE THREAD

**Issue by SamMackrill** [StevenLiekens/gw2sdk#132]
Very useful,
Can get a list of characters just fine
I am trying to count Laurels, can't seem to find how to access the Wallet or any calls v2/wallet in the source

**Comment by StevenLiekens** [comment]
Hello,

Thanks for evaluating my code.

The wallet endpoint was not implemented yet so I added it just now. You can find the `WalletService` in the `GW2SDK.Accounts.Wallets` namespace.

Development packages are not auto-updating right now because of a problem in the automated build, but I'll fix that asap.

Lmk if you need anything else.

**Comment by StevenLiekens** [comment]
@SamMackrill a new development package is available that contains the Wallet service
